### ISSUE TITLE
Avoid unintentional HPA replicas increase during deployment updates

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1789]
**Describe the bug**
We currently use autoscaling v2beta2 API for broker deployments. But the it seems causing unintentional autoscaling during deployment update. Found related issue https://github.com/kubernetes/kubernetes/issues/84142, and in comment https://github.com/kubernetes/kubernetes/issues/84142#issuecomment-544865183 it specifically points out that v2beta2 is impacted.

**Comment by AlexandraRoatis** [comment]
- I verified that the unintended increase in replicas occurs and it escalates substantially for fast successive updates (in my test consecutive `kubectl rollout restart`).
- Switching to version `v1` may not be desirable because it appears that it only supports autoscaling on CPU:
    - https://godoc.org/k8s.io/api/autoscaling/v1#HorizontalPodAutoscalerSpec
    - https://cloud.google.com/kubernetes-engine/docs/how-to/horizontal-pod-autoscaling#api-versions
- However, I verified that removing the memory metric while still using `v2beta2` substantially improves the situation. One additional replica is created only after 3 consecutive restarts, while in the case when memory is kept there is one additional replica per restart.
- The issues https://github.com/kubernetes/kubernetes/issues/95021 and https://github.com/kubernetes/kubernetes/pull/89465 may also be related and are worth following for updates.

**Comment by yolocs** [comment]
@Ectelion @cathyzhyi 

How comfortable will we be if we remove memory from HPA?

**Comment by Ectelion** [comment]
This is an interesting result, thanks for finding this out!

In the current version, we have very different worst cases for the CPU consumption and for memory consumption. This can be seen on the plot below, where we have high CPU / low memory series of experiments to the left and, contrary, low CPU / high memory results to the right.

![image](https://user-images.githubusercontent.com/1721518/95823961-5bab6200-0ce3-11eb-9a04-bae8cc5adc1a.png)

So, the CPU-based metric alone doesn't account for all the cases, thus, removing the memory-based autoscaling metric may be quite limiting for the current version. I wonder if there is something inherently problematic with the memory-based autoscaling or is this more of an upgrade issue that is being surfaced when the memory metric is enabled? 

Maybe it would be best to make such a switch when other means of autoscaling will be introduced, like those based on custom metrics? Otherwise, one alternative mitigation I could think of is to either temporarily adjust _minReplicas_ in the deployments to the latest pre-upgrade value for the duration of the upgrade. Another consideration is: possible disruptions during upgrade are somewhat expected; not sure about Knative customer base in particular, but many enterprises tend to perform upgrades during dark/quite hours. Not being able to scale in the above circumstance during the normal non-upgrade hours, more often than not, may probably be even more problematic.

**Comment by grantr** [comment]
Notes from sync:
- Test the number of replicas added during update
- If 2x, try to increase speed of scaledown
- if +1, do nothing

**Comment by zhongduo** [comment]
Do we still need to work on this? From the comment it seems that this is already fixed upstream in k8s.
https://github.com/kubernetes/kubernetes/issues/84142#issuecomment-629564829

**Comment by grantr** [comment]
Downgrading this to P2.

**Comment by cathyzhyi** [comment]
I am still seeing this issue with `v1.18.12-gke.1201`
Seems there is something wrong with the memory usage that `kubectl get hpa default-brokercell-fanout-hpa -n cloud-run-events --watch` shows the following output after `ko apply -f configs`
```
NAME                            REFERENCE                              TARGETS                   MINPODS   MAXPODS   REPLICAS   AGE
default-brokercell-fanout-hpa   Deployment/default-brokercell-fanout   19390464/1000Mi, 0%/50%   1         10        1          8d
default-brokercell-fanout-hpa   Deployment/default-brokercell-fanout   19390464/1000Mi, 0%/50%   1         10        1          8d
default-brokercell-fanout-hpa   Deployment/default-brokercell-fanout   10437973333m/1000Mi, 0%/50%   1         10        2          8d
default-brokercell-fanout-hpa   Deployment/default-brokercell-fanout   19675818666m/1000Mi, 0%/50%   1         10        2          8d
default-brokercell-fanout-hpa   Deployment/default-brokercell-fanout   19735893333m/1000Mi, 0%/50%   1         10        2          8d
default-brokercell-fanout-hpa   Deployment/default-brokercell-fanout   19806890666m/1000Mi, 0%/50%   1         10        2          8d
default-brokercell-fanout-hpa   Deployment/default-brokercell-fanout   19943424/1000Mi, 0%/50%       1         10        2          8d
```
The outputs from `kubectl top pod -n cloud-run-events` are like the following and looks normal. 
```
 NAME                                          CPU(cores)   MEMORY(bytes)
   12 controller-5cdd787655-znm8g                   20m          37Mi
   11 default-brokercell-fanout-646fd4f948-j69m6    5m           18Mi
   10 default-brokercell-fanout-646fd4f948-xmxm9    5m           19Mi
    9 default-brokercell-fanout-68d7775684-cgvhh    7m           18Mi
    8 default-brokercell-ingress-54cb78f4c5-nn5nc   1m           16Mi
    7 default-brokercell-ingress-84855bfdd9-cvn7f   1m           16Mi
    6 default-brokercell-ingress-84855bfdd9-dv9zl   1m           17Mi
    5 default-brokercell-retry-5786464778-qbsbv     1m           17Mi
    4 default-brokercell-retry-5786464778-zrkt2     4m           18Mi
    3 default-brokercell-retry-5cd9f767cb-lb4kr     3m           18Mi
    2 webhook-7557bfc4c6-62dgp                      6m           28Mi
```

**Comment by zhongduo** [comment]
hmm, I just tried with master, and didn't see the problem.

**Comment by zhongduo** [comment]
I was also able to reproduce the problem, which I believe also explain the unexpected number of brokercell pods in the upgrade test. After syncing with Yi offline and taking a closer look at the output of HPA, `19675818666m` is actually ~19Mi as `m` means 0.001. However such a unit shouldn't exist for memory usage in the first place, so I am inclined to believe that this is a bug in HPA. We should try a different version of HPA and see if the problem is fixed before spending too much time here.

**Comment by sumitjainn** [comment]
Hi, can someone please confirm if this issue is fixed on master?
